steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: docker-login
    entrypoint: 'bash'
    args: ['-c', 'docker login --username=haipiaodev --password=$$PASSWORD']
    secretEnv: ['PASSWORD']
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', '--depth=1', 'https://github.com/HaiPiaoAPP/haipiao.git']
    id: git-clone
    waitFor: ['-']
  - name: 'gcr.io/cloud-builders/gradle'
    args: ['assemble']
    id: gradle
    waitFor: ['git-clone']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t=haipiaodev/registration:${_REGISTRATION_VERSION}', 'registration']
    id: docker-build-registration
    waitFor: ['gradle']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'haipiaodev/registration:${_REGISTRATION_VERSION}']
    id: docker-push-registration
    waitFor: ['docker-build-registration']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t=haipiaodev/user-service:${_USER_SERVICE_VERSION}', 'user-service']
    id: docker-build-user-service
    waitFor: ['gradle']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'haipiaodev/user-service:${_USER_SERVICE_VERSION}']
    id: docker-push-user-service
    waitFor: ['docker-build-user-service']

  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f=deployment/k8s/app/namespace.yaml']
    id: kubectl-create-ns
    waitFor: ['-']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=asia-east2-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=hp-cluster'
  - name: 'gcr.io/$PROJECT_ID/kustomize'
    args: ['build', 'deployment/k8s']
    id: kustomize-deploy
    waitFor:
      - kubectl-create-ns
      - docker-push-registration
      - docker-push-user-service
    env:
      - 'APPLY=true'
      - 'CLOUDSDK_COMPUTE_ZONE=asia-east2-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=hp-cluster'
      - 'GCLOUD_PROJECT=hp-project-256305'

secrets:
  - kmsKeyName: 'projects/hp-project-256305/locations/global/keyRings/haipiao-keyring/cryptoKeys/haipiao-docker'
    secretEnv:
      PASSWORD: 'CiQAKysa5d6F6Qv/FWHPFJaQHZ2//NzULQi9Bkuvn6zC4LgUOiASNAAo9bUBxhLN9FJxYyZnTFJKyT43n98X0N9GuI+igfRP6H6ZXDx3rIrln56A5d6Gn+N55Fw='
timeout: 600s
substitutions:
  _REGISTRATION_VERSION: 0.0.1
  _USER_SERVICE_VERSION: 0.0.1
  _ARTICLE_SERVICE_VERSION: 0.0.1
