steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: docker-login
    entrypoint: 'bash'
    args: ['-c', 'docker login --username=haipiaodev --password=$$PASSWORD']
    secretEnv: ['PASSWORD']
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', '--depth=1', 'https://github.com/HaiPiaoAPP/haipiao.git']
    id: git-clone
    waitFor: ['-']
  - name: 'gradle:jdk11'
    args: ['gradle', 'assemble']
    id: gradle
    waitFor: ['git-clone']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t=haipiaodev/registration:${_REGISTRATION_VERSION}', 'registration']
    id: docker-build-registration
    waitFor: ['gradle']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'haipiaodev/registration:${_REGISTRATION_VERSION}']
    id: docker-push-registration
    waitFor: ['docker-build-registration']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t=haipiaodev/user-service:${_USER_SERVICE_VERSION}', 'user-service']
    id: docker-build-user-service
    waitFor: ['gradle']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'haipiaodev/user-service:${_USER_SERVICE_VERSION}']
    id: docker-push-user-service
    waitFor: ['docker-build-user-service']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t=haipiaodev/article-service:${_ARTICLE_SERVICE_VERSION}', 'article-service']
    id: docker-build-article-service
    waitFor: ['gradle']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'haipiaodev/article-service:${_ARTICLE_SERVICE_VERSION}']
    id: docker-push-article-service
    waitFor: ['docker-build-article-service']

  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f=deployment/k8s/app/namespace.yaml']
    id: kubectl-create-ns
    waitFor: ['-']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=asia-east2-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=hp-cluster'

  - name: 'gcr.io/$PROJECT_ID/kustomize'
    args: ['build', 'deployment/k8s/app']
    id: kustomize-deploy-0-replicas
    waitFor:
      - kubectl-create-ns
      - docker-push-registration
      - docker-push-user-service
      - docker-push-article-service
    env:
      - 'APPLY=true'
      - 'CLOUDSDK_COMPUTE_ZONE=asia-east2-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=hp-cluster'
      - 'GCLOUD_PROJECT=haipiao-dev'

  - name: 'gcr.io/$PROJECT_ID/kustomize'
    args: ['build', 'deployment/k8s']
    id: kustomize-deploy
    waitFor:
      - kustomize-deploy-0-replicas
    env:
      - 'APPLY=true'
      - 'CLOUDSDK_COMPUTE_ZONE=asia-east2-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=hp-cluster'
      - 'GCLOUD_PROJECT=haipiao-dev'


secrets:
  - kmsKeyName: 'projects/haipiao-dev/locations/global/keyRings/haipiao-keyring/cryptoKeys/haipiao-docker'
    secretEnv:
      PASSWORD: 'CiQAWjwyCkAV9LwKEbyW6PqT3moVBoQowQdfPND4NaFFnEvNl8cSMwA7UXFh9aDjNWBSB3aAccG4jGaOTDQ5D0dHOK1sSMgUathmwr+OLbsVkOUf26Qxfjl97A=='
timeout: 600s
substitutions:
  _ARTICLE_SERVICE_VERSION: 0.0.1
  _REGISTRATION_VERSION: 0.0.1
  _USER_SERVICE_VERSION: 0.0.1
