apiVersion: v1
kind: Service
metadata:
  name: postgres-lb
  namespace: testk8s
  labels:
    app: postgres
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 48375
      targetPort: 5432
  selector:
    statefulset.kubernetes.io/pod-name: haipiao-postgres-0
    app: postgres
