language: java

jdk:
  - openjdk11

services:
  - docker

install:
  - ./scripts/install-dependencies.sh

before_script:
  - export PATH=$(pwd)/bin:$PATH
  - docker pull redis:5.0.5
  - docker pull haipiaodev/hp-postgres:0.0.4
  - docker-compose -f ./scripts/stack.yml up > /dev/null &

script:
  - PROJECT_ROOT=$(pwd) ENV=dev ./gradlew build

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
