# Adds namespace to all resources.
namespace: testk8s

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: haipiao-

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

resources:
  - app/ingress.yaml
  - app/configmap.yaml
  - app/postgres.yaml
  - app/redis.yaml
  - app/registration.yaml
  - app/user-service.yaml
  - app/article-service.yaml
  - app/image-service.yaml
