# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: haipiaodev/hp-postgres:0.0.1
    restart: always
    ports:
      - 48375:5432
    environment:
      POSTGRES_PASSWORD: example

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080