# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: haipiaodev/hp-postgres:0.0.5
    restart: always
    ports:
      - 48376:5432
    environment:
      - POSTGRES_PASSWORD=example

  redis:
    image: redis:5.0.5
    ports:
      - 16379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes