apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
data:
  application.properties: |
    spring.main.banner-mode=off
    redis.service=haipiao-redis.testk8s.svc:16379
    redis.dbIndex=0
    redis.defaultTTL=600
    postgres.driverClassName=org.postgresql.Driver
    postgres.url=jdbc:postgresql://haipiao-postgres.testk8s.svc:48375/postgres
    postgres.username=postgres
    postgres.password=haipiaodev
    sts.stsEndpoint=sts.aliyuncs.com
    sts.ossEndpoint=http://oss-cn-hangzhou.aliyuncs.com
    sts.accessKeyId=LTAI4FvaHAkhBwxKrjJ5W83N
    sts.accessKeySecret=kj46BvWo07uxlkirvzFrtJE81gwPva
    sts.roleArn=acs:ram::1893264966337206:role/haipiao-image-uploader
  postgres: haipiaodev
