apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
data:
  application.properties: |
    spring.main.banner-mode=off
    redis.service=haipiao-redis.testk8s.svc:16379
    redis.dbIndex=0
    redis.defaultTTL=600
    postgres.driverClassName=org.postgresql.Driver
    postgres.url=jdbc:postgresql://haipiao-postgres.testk8s.svc:5432/postgres
    postgres.username=postgres
    postgres.password=haipiaodev
    sts.stsEndpoint=sts.aliyuncs.com
    sts.ossEndpoint=http://oss-cn-hangzhou.aliyuncs.com
    sts.accessKeyId=LTAI4FvaHAkhBwxKrjJ5W83N
    sts.accessKeySecret=kj46BvWo07uxlkirvzFrtJE81gwPva
    sts.roleArn=acs:ram::1893264966337206:role/haipiao-image-uploader
    sms.testing=false
    sms.domain=dysmsapi.aliyuncs.com
    sms.region=cn-hangzhou
    sms.accessKeyId=LTAI4FqraELkYj7NisESNPGA
    sms.accessKeySecret=ad4Lptzm07rafIakPhSTKleI9tXAZP
    # 海漂的unicode
    sms.signature=\u6d77\u6f02
    sms.template=SMS_179225837
    # log4j2 properties
    logging.config=/config/log4j2.xml
    # expose metrics through spring boot actuactor
    management.endpoints.web.exposure.include=*
    management.endpoints.web.exposure.exclude=
  log4j2.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration>
        <Appenders>
            <Console name="Console" target="SYSTEM_OUT" follow="true" >
                <PatternLayout pattern="%d loglvl=%-5p rId=%X{REQUEST_UUID} ip=%X{IP} appname=%X{APP_NAME} actionKpi=%X{ACTION_KPI} [%t] %c - %m%n" />
            </Console>
        </Appenders>

        <Loggers>
            <!-- LOG everything at INFO level -->
            <Root level="info">
                <AppenderRef ref="Console" />
            </Root>
        </Loggers>
    </Configuration>
  postgres: haipiaodev
