apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: primary-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: haipiao.app
      http:
        paths:
          - path: /user
            backend:
              serviceName: user-service
              servicePort: 48375
          - path: /category
            backend:
              serviceName: user-service
              servicePort: 48375
          - path: /recommendation/user
            backend:
              serviceName: user-service
              servicePort: 48375
          - path: /group/[0-9]+/user/[0-9]+
            backend:
              serviceName: user-service
              servicePort: 48375
          - path: /security-code
            backend:
              serviceName: registration-service
              servicePort: 48376
          - path: /article
            backend:
              serviceName: article-service
              servicePort: 48375
          - path: /image
            backend:
              serviceName: image-service
              servicePort: 48375
  tls:
    - hosts:
        - haipiao.app
      secretName: haipiao-tls
