# Adds namespace to all resources.
namespace: testk8s

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: haipiao-

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

resources:
  - ingress.yaml
  - configmap.yaml
  - postgres.yaml
  - redis.yaml
  - registration.yaml
  - user-service.yaml
  - article-service.yaml
  - image-service.yaml

patchesStrategicMerge:
  - set-replicas-patch.yaml
