apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: testk8s
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    statefulset.kubernetes.io/pod-name: haipiao-postgres-0
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  serviceName: postgres-headless
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: haipiaodev/hp-postgres:0.0.5
          imagePullPolicy: Always
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: postgres
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - name: postgressvc
              containerPort: 5432
          volumeMounts:
            - name: postgres
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres
          gcePersistentDisk:
            pdName: postgres-volume
            fsType: ext4
